/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Login: typeof import('@/views/auth/Login.vue')['default']
    Overview: typeof import('@/views/Overview.vue')['default']
    Project: typeof import('@/views/Project.vue')['default']
    ProjectSettings: typeof import('@/views/ProjectSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Welcome: typeof import('@/views/Welcome.vue')['default']
  }
}
